[Feat] 도구 정보 뷰 수정 및 추가 #13
3chuu/Poketochip pull request #21
Opened 2024-02-07 08:22 UTC by empty005

## Changes

- 도구, 가방 목록 뷰 추가
- 팝업 및 아코디언 뷰는 수정 및 개편 중

<br>
## To Reviewers
팝업은 아직..
-

2024-02-08 14:49 UTC, akrudal requested changes
앞서 본 파일들이 다수 있는듯하여 순차적으로 머지하고 바뀐 파일들만 다시 보는걸로 하겠습니다!

2024-02-11 10:40 UTC, yoonjiho37 approved these changes
고생하셨습니다!

2024-02-11 10:40 UTC, yoonjiho37 commented on Poketochip/Projects/Presentation/Sources/Bag/Model/SectionModel.swift
Section이라는 단어는 전역적으로 쓰일 수 있는 의미의 단어라는 생각이 들고
이것 만으로는 어떤 역할을 하는 Model인지 잘 모르겠습니다.

2024-02-11 10:40 UTC, yoonjiho37 commented on Poketochip/Projects/Presentation/Sources/Bag/View/BagDetailViewController.swift
TableView Delegate, DataSource가 public으로 풀리는 상황이 잘 와닿지 않은데 
어떻게 해서 풀리게 되었는지 궁금합니다.

2024-02-11 10:40 UTC, yoonjiho37 commented on Poketochip/Projects/Presentation/Sources/Bag/View/Cell/BagTableViewCell.swift
경미님이 저에게도 짚어주신 부분인데 Cell의 setData가 public으로 사용될만한 이유가 있으실까요?

2024-02-11 17:01 UTC, empty005 commented on Poketochip/Projects/Presentation/Sources/Bag/Model/SectionModel.swift
해당 모델은 임시 모델로 아코디언 확대 및 팝업 용으로 쓸 사항으로 기능 확인상 더미로 사용 되었습니다.

2024-02-11 17:20 UTC, empty005 commented on Poketochip/Projects/Presentation/Sources/Bag/View/BagDetailViewController.swift
해당 public viewController를 쓰고 tableview를 쓰니까 public으로 사용 할 수 밖에 없어서 사용 했습니다.

2024-02-11 17:22 UTC, empty005 commented on Poketochip/Projects/Presentation/Sources/Bag/View/Cell/BagTableViewCell.swift
혹시나 모듈 사용상에서 셀을 다시 사용 할 수 있거나 외부 데이터를 받는다고 생각해서 해당 셀의 setData가 퍼블릭으로 사용 되어야 하나라고 생각되어서 설정해두었습니다.

2024-03-13 06:11 UTC, akrudal approved these changes
고생하셧습니다!

2024-03-13 10:53 UTC, merged